services:
  backend:
    image: golang:1.27-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - PORT=9090
    ports:
      - "8080:9090"
    command: go run main.go
